INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Alluring Tail Feather', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Amazing Lock', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Amethyst Gem', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Amethyst Pebbles', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Amethyst Shard', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ancient Flowerpot', N'', 222, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Angel Amaryllis', N'', 3000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Angelfly Wing', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Animal Fang', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Animal Glue', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Antlion Silk', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Antitoxin', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Applesauce', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Aqua Pearl', N'', 180, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Aqua Pearl Necklace', N'', 6480, 1)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Arcane Seed', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Arctic Skin', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Attack Pincer', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Augery Apple', N'', 6, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Avian Egg', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Baby Scuffleshroom', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Back Bacon', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Balance Brownie', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bally', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bally Milk', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bally Wool', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bamboo Flowerpot', N'', 750, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bashon Coat', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bashon Hide', N'', 40, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bashon Leather', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bashon Meat', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bat Fang', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bat Wing', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Beak Trumpet', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bear Hug Rug', N'', 480, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Beet Boar', N'', 650, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Beet Boar Back Bacon', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Beet Boar Back Bacon Strip', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Beholder Bud', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Benediction Eggs', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bewitched Orange Juice', N'', 26, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bewitched Apple Juice', N'', 84, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bewitched Grape Juice', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bewitched Pineapple Juice', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bewitched Lemon Juice', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Bat Wing', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Bug Egg', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Horn', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Leather', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Skin', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Wool', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Birch Log', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bird Feathers', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bird Meat', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bird Beak', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bird Claw', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Birch Lumber', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Black Bug’s Blood', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Black Fur', N'', 6, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Black Lotus', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Black Lotus Extract', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Black Peppercorn', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Blinding Acid', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Blizzard''s Breath', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Blue Dye', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Deafness', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Fire', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Gravel', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Ice', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Radiance', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Sickening', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bomblet of Stunning', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Brass Flowerpot', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Brass Ingot', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Brittany Log', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bronze Flowerpot', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bronze Ingot', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bronze Rod', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bucktooth Bunny', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Buckwheat', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Buckwheat Flour', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Buddy Ale', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bug Meat', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Bum Rum', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Burlap Cloth', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Horn', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Leather', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Meat', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Skin', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Big Sheep Wool', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Calamity Coconut', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Carapace Chunk', N'', 90, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cashmere Cloth', N'', 3000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Catalyzer', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Caverncrawler Cocoon', N'', 900, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Celestial Holy Water', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Centipede Cocoon', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Centipede Silk', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ceremonial Beak Trumpet', N'', 3500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Chalet Wine', N'', 40, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Chamelyanis', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Chantelle White Wine', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Chromite Chunk', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Chromium Ingot', N'', 225, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Chrono Chrysanthemum', N'', 3000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Clay Flowerpot', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cloaker Hide', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cloaker Leather', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Clucker', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Colorful Spine Arrow / Bolt', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Come, Apophis (book)', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Comet Fragment', N'', 1125, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Conch Shell', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Coniferous Carrot', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Copper Ore', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Copper Ingot', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cottontail', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cotton Cloth', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cotton Seed', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cow Milk', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crab Meat', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crab Shell', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cream of Myconid', N'', 345, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crème de la Crème', N'', 40, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crimson Cloth', N'', 650, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crispy Cod', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Croc Hide', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Croc Leather', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cruel Tentacle', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crusty Carapace', N'', 900, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crying Cod', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crystal Flowerpot', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Crystallizing Potion', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cure Tiny Wounds Potion', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cure Light Wounds Potion', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cure Moderate Wounds Potion', N'', 310, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cure Serious Wounds Potion', N'', 750, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cure Critical Wounds Potion', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dandy Brandy', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Darkening Arrow', N'', 110, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Darkmantle Skin', N'', 575, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Deer Meat', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dehydrator', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Deluxe Dirt', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Demon Husk', N'', 666, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Deodorizer', N'', 162, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Diamond Pebbles', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Diamond Shard', N'', 850, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Diamond Gem', N'', 3500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Diabolic Grapes', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dino Hide', N'', 180, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dino Leather', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dino Meat', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dissolving Potion', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Do It Yourself Surgery (book)', N'', 425, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dog Feathers', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dog Hide', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dog Jerky', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dog Leather', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dog Meat', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Draconic Leather', N'', 5000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragon Blood', N'', 550, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragon Bone', N'', 1600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragon Claw', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragon Heart', N'', 25000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragon Skin', N'', 3400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragonite Chain', N'', 1600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragonite Ingot', N'', 700, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragonite Rod', N'', 175, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragonite Ore', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragonite Scales', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dragonite Sheet', N'', 3200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Draconic Cloth', N'', 10800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dream Flower', N'', 950, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dry Bones', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dungeon Daisy', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Dust of Tracelessness', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Electric Antenna', N'', 210, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Electrosoil', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Elixir of Love', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Elixir of Truth', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Elixir of Fire Breath', N'', 1100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Elm Log', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Emerald Gem', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Emerald Lettuce', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Emerald Pebbles', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Emerald Shard', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Brittany Log', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Brittany Lumber', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Elm Log', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Elm Lumber', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Olde Oak Log', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Olde Oak Lumber', N'', 1500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Rosewood Log', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Rosewood Lumber', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Mahogany Log', N'', 1800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enchanted Mahogany Lumber', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Enormous Egg', N'', 160, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Epona', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Epona Brick', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ether', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Everburning Torch Set (5)', N'', 550, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Evil Eyeball', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Exalted Horn', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Extraction Liquid', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fabled Fowl Meat', N'', 550, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fat of Funghi', N'', 110, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fertilizer (Weak)', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fertilizer (Moderate)', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fertilizer (Mighty)', N'', 5000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fiend Blood', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fiend Flowerpot', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fiery Feathers', N'', 55, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fiery Fern', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fiery Yarlax Arrow / Bolt', N'', 125, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fire Antler', N'', 125, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fire Leaf', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Firesand', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Firolena Hide', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Firolena Leather', N'', 40, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fish Eggs', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fish Scale', N'', 37, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fisherman’s Filet', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Flail Snail Gel', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Flail Snail Slime', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fortress Cheese', N'', 18, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fowl Meat', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Frisky Whiskey', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Frost Turnip', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fug Fish', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Fug Fish Filet', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gardening Gloves', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gardening Gloves Supreme', N'', 1300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Garlic Baked Bread', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Beak', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Bird Fan', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Compound Eye', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Crab Shell', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Feather', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Stinger', N'', 42, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Giant Tusk', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gigas Hide', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gigas Skull', N'', 5000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Glacial Horn', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Glimmering Kernel', N'', 1550, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Snail Flesh', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Glow Nose', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gnarley Barley', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gorgon Butter', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gorgon Hide', N'', 950, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Goblin Head', N'', 70, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gold Chunk', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gold Ingot', N'', 700, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gold Ore', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Golden Shovel', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Golem Uprising! (book)', N'', 175, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Grain Seed', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Grandma Was A Succubus (book)', N'', 69, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Growfast Alpha', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Growfast Omega', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Grub Cocoon', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Grub Silk', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gryph Feathers', N'', 850, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gumbobo', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gustka Feathers', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Gygax Garlic', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Healing Herb Vine', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hellhound Pelt', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Herb Seed', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hex Panther Coat', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hex Panther Leather', N'', 70, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hip Hops', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hippagryph Comb', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hippagryph Egg', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hippagryph Hatchling', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hippogryph Hatchling', N'', 3000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Horn Flowerpot', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Horse Hide', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Horse Leather', N'', 40, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Horse Meat', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Holy Water', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hooch Scotch', N'', 7, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Homesweet Honey', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Huge Feather', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Humchi Feathers', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hush Flower', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Hydra Skin', N'', 2500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ice Claw', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ice Tusk', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ice Vanilla', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ingredients Pack', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Insect Fan', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Insect Wing', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Inverse Potion', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Chain', N'', 80, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Ingot', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Rod', N'', 6, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Mandible', N'', 22, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Ore', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Scales', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Sheet', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Iron Sphere', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ironweave Cloth', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jackalope Antler', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jackalope Hide', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jackalope Leather', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jagged Antler', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jalapapepper', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jelly Concentrate', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jelly Mucus', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Jewel Gryph Arrow / Bolt', N'', 220, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kane''s Sugar', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Karoro Feathers', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Karpathi', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Keke Lime', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kingdom Dove Feathers', N'', 55, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kobald Skin', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kobald Leather', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Koda Lily (restricted)', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Koda Powder (restricted)', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kodiak Pelt', N'', 370, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kori-Kori Feathers', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kronus Pebble', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kronus Shard', N'', 850, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kronus Gem', N'', 3500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Kytar', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Large Mandible', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lesser Leviathan', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Leviathan Hide', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Liberty Leaf', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lich Crème (illegal)', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lightning Lily', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lionshrimp', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'(Livestock) Clucker', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'(Livestock) Oinker', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'(Livestock) Bali', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'(Livestock) Truffalo', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'(Livestock) Beet Boar', N'', 650, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lizard Egg', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lizard Leather', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lizard Skin', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lizard Tail', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lobster Meat', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Long Fuse', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Longhorn', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Love Potion', N'', 160, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lowhog Hide', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lucky Clovers', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lucky Foot', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lulu Lemon', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Luminous Brass Ingot', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Luminous Silver Ingot', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Luminous Gold Ingot', N'', 1500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Luminous Platinum Ingot', N'', 5500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Luminous Moonlight Ingot', N'', 9000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Lurid Liqueur', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Marii Tea', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Bean', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Feather', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Flowerpot', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Skull', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Fire)', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Ice)', N'', 80, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Wind)', N'', 80, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Earth)', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Lightning)', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Water)', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Darkness)', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Time)', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magic Orb (Light)', N'', 4000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Magical Horse Hide', N'', 625, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mahogany Log', N'', 7, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Malt of Malevolence', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Manticore Hide', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Manticore Leather', N'', 650, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Marshmantle Egg', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mean Bean', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mean Tree Pod', N'', 1800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Meownix Hide', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Meownix Leather', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Metallic Nut', N'', 2200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Midnight Cloth', N'', 5000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Midnight Oil', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mindflayer Moonmelon', N'', 555, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Miner''s Pick', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mistletoe Thistle', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Molar of Monster', N'', 215, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Molson Caitonian', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Monkey Hide', N'', 70, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Monkey Leather', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Moon Elf Love Slave (book)', N'', 999, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Moonlight Ingot', N'', 4500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Moondust Pile', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mothman Meat', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mountain Ram Hide', N'', 230, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mountain Ram Leather', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mountain Ram Wool', N'', 2500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mulsim', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Mushroom Poison Potion', N'', 225, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Moderate Mushroom Poison Potion', N'', 345, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Naga Skin', N'', 252, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Neener Tooth', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Neutralize Poison Potion', N'', 625, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nightsteel Chain', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nightsteel Crown', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nightsteel Ingot', N'', 550, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nightsteel Rod', N'', 137, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nightsteel Scales', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nightsteel Sheet', N'', 2400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Nimrod Nut', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Occultic Orange', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Octofunghi Dust', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Octopi Funghi', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Octovole Tail', N'', 125, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Oilsand', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Oinker', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Olde Oak Log', N'', 6, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Opal Pebbles', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Opal Shard', N'', 850, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Opal Gem', N'', 3500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Fire', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Ice', N'', 80, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Wind', N'', 80, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Earth', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Lightning', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Water', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Darkness', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Orb of Light', N'', 4000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Oregano', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Oregano Flakes', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ovesized Eyeball', N'', 480, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pantheron Eye', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pantheron Hide', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pantheron Leather', N'', 60, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Paralyzing Poison', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Peppercorn Sauce', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Petri Seed', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Petrifying Acid', N'', 475, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Petrifying Potion', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Phoenix Feathers', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pig Skin', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pig Leather', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pinewood Mint', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pirate’s Punch', N'', 44, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Platinum Ore', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Platinum Ingot', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Plumpkin', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Plumpkin Flesh', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Plumpkin Flowerpot', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Plumpkin Seed', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Bomblet', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Claw', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Dust', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Leaf', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Paste', N'', 380, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Princess', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poison Sac', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Polarcrystal Gem', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Polarcrystal Pebbles', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Polarcrystal Shard', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pool Pirahna', N'', 145, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Poptato', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Pork Chop', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Prehistoric Egg', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Primitive Ceremonial Dagger', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Primordial Soup', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Princess Toadstool', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Purple Dye', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Quickening Potion', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Quicksand', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Quicksilver (ball)', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rabbit Leather', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rabbit Meat', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rabbit Pelt', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Raging Red Onion', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rain Rose', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rolling Hill Honey', N'', 77, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Razorfin Flail', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Red Dragon Royal', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Red Dye', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Red Reed Funghi', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Red Rock', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Redsteel Chain', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Redsteel Ingot', N'', 120, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Redsteel Rod', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Redsteel Scales', N'', 180, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Redsteel Sheet', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Regen Potion (Tiny)', N'', 55, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Regen Potion (Light)', N'', 175, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Regen Potion (Moderate)', N'', 245, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Regen Potion (Serious)', N'', 325, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Regen Potion (Critical)', N'', 555, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Remedial Poppy', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Restoration Root', N'', 275, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Revival Radish Heart', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rock Child', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rodent Pelt', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Romanov Leaves', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rosewood Log', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Royal Jelly', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Royal Tea', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Royal Tea Leaves', N'', 4, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ruby Gem', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ruby Pebbles', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ruby Shard', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rug Ray', N'', 225, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Runnel Shark', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Rusty Flowerpot', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sabre Tooth', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Salt of the Sea', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sandguin Feathers', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sandy Fish Arrow / Bolt', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sapphire Pebbles', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sapphire Shard', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sapphire Gem', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Satyr Horn', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scorpion Husk', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scroll of 0 level spell', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scroll of 1st level spell', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scroll of 2nd level spell', N'', 160, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scroll of 3rd level spell', N'', 375, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scroll of 4th level spell', N'', 600, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Scroll of 5th level spell', N'', 950, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sea Serpent Hide', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sea Serpent Leather', N'', 1400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Segmented Legs', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Seraph Feathers', N'', 700, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Shard Venom Sac', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sharp Beak', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sharp Fin (small)', N'', 23, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sharp Fin (medium)', N'', 23, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sharp Fin (large)', N'', 46, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sharp Fin (huge)', N'', 46, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sharp Spine', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sheepskin', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sheep Horn', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Shikari Pelt', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Shikari Leather', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Short Fuse', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Shorthorn', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Silent Pot Shard', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Silver Horn', N'', 1750, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Silver Ingot', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Silver Insect Hairpin', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Silver Ore', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Silver Shovel', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Skeleton Shamrock', N'', 3000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Skin of Dread Beast', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sleep Arrow', N'', 85, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Slime Oil', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Small Iron Mandible', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Snail Scales', N'', 65, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Snake Meat', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Snake Oil', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Snowpowder', N'', 8, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sparkling White Wine', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spectral Stem', N'', 575, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spectre Syrup', N'', 75, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spider Eggplant', N'', 9, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spider Eye', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spider Ink', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spider Satin', N'', 450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spider Silk', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spider Web', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spine Vine', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (0 Circle)', N'', 225, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (1st Circle)', N'', 690, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (2nd Circle)', N'', 1290, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (3rd Circle) ', N'', 2390, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (4th Circle)', N'', 3690, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (5th Circle)', N'', 5490, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (6th Circle)', N'', 7690, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (7th Circle)', N'', 10290, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (8th Circle)', N'', 13290, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spirit Orb (9th Circle)', N'', 16690, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spring Water', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Spyglass', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Star Seed', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Stardust', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Steelweave Silk', N'', 2000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Stillborn Plumpkin', N'', 70, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Stone Morningstar Wand', N'', 5000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Storm Corn', N'', 5, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sugarkane', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Sunrise Oil', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swamp Tomato', N'', 3, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swampslicer', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swampslicer Dicer', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Hide', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Horn', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Leather, small', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Leather, medium', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Leather, large', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Sirloin', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Swiftcow Ribs', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Syrnx Feathers', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Terra Root', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'The Passionate Yeti (book)', N'', 27, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Thicket Beet', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Thistle Snake Head', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Thrashing Wheat', N'', 2, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Thornmelon', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Thunderstone', N'', 30, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tin Ore', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tinfoil Hat', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tome of [Magic], Vol. I', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tome of [Magic], Vol. II', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tome of [Magic], Vol. III', N'', 750, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tome of [Magic], Vol. IIII', N'', 1500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tome of [Magic], Vol. V', N'', 3000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Topaz Pebbles', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Topaz Shard', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Topaz Gem', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tornado Tulip', N'', 1000, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tortosaur Shell', N'', 1280, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Trailspringer Mitten', N'', 800, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Trawler’s Meat', N'', 27, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tree Seed', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Trembull Hide', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Trembull Leather', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tribronodon Shell Fragment', N'', 500, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tritanium Chain', N'', 700, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tritanium Ingot', N'', 350, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tritanium Rod', N'', 87, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tritanium Scales', N'', 370, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tritanium Sheet', N'', 1300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tritanium Skeleton', N'', 2450, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Truffalo', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Tycondria', N'', 515, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Ultra Sharp Toenail', N'', 150, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Unholy Water', N'', 325, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Universal Solvent', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Unwilded Oats', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Urex Feathers', N'', 50, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Varkmaw Hide', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Varkmaw Leather', N'', 300, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Veggie Seed', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Velvet Cloth', N'', 1200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Venom Fang', N'', 37, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Venom of Fire Beetle', N'', 380, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Venom of Centipede', N'', 225, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Venom of Scorpion', N'', 250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Venom of Spider', N'', 175, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Venom of Viper', N'', 260, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Red Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Azure Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Green Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Yellow Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Purple Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant White Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Brown Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vibrant Black Fur', N'', 100, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Vicious Dog Arrow / Bolt', N'', 12, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Violaceous Cloth', N'', 2250, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Volcano Sauce', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Voodoo Pineapple', N'', 40, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Walrus Pelt', N'', 20, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'War Won Ton', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wasp Venom', N'', 15, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Water', N'', 1, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Cocoon Flowerpot', N'', 200, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wolf Head', N'', 68, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wolf Pelt', N'', 25, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wool Cloth', N'', 220, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wyrm Skull', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wyrm Skull Helm', N'', 45, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Wyvern Skin', N'', 1700, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Yarlax Feathers', N'', 400, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Yeti Fur', N'', 35, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Zentoki Moss', N'', 10, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Zephyr Ash', N'', 8, 0)
INSERT [dbo].[items] ([name], [description], [cost], [usable]) VALUES (N'Zinc Ore', N'', 20, 0)